# Generated by Django 5.0.4 on 2024-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='title',
            field=models.CharField(default='Transcript1', max_length=255),
            preserve_default=False,
        ),
    ]
